### ISSUE TITLE
No ability to set shipping $ value in admin until page refreshed

### ISSUE THREAD

**Issue by ctadlock** [magepal/magento2-custom-shipping-rate#6] opened 2018-04-17 01:53 UTC
I can reliably reproduce an error when placing an admin order where the admin is unable to set the $ amount of the shipping as they are all already set at $0. The solution is to refresh the page (press return in address bar), then it works. Ive been unable to determine the cause; there are no network or console errors. Its for an existing customer, the choice of address, payment method.. don't seem to have an effect. 

It "feels" like a state timing issue, where when the page is first loaded some flag isn't set properly and the display logic acts as if the amount as been set to $0. Refreshing the page keeps all the other data about the order, but when the "get shipping rates" link is clicked, the appropriate UI is shown allowing the admin to set the $ amount.

Magneto 2.2.3
PHP 7.1
Latest Chrome on latest Mac

![image](https://user-images.githubusercontent.com/1539397/38844052-ad6db44a-41a6-11e8-88fa-860844a5a255.png)

**Comment by srenon** [comment] 2018-04-17 10:33
1. You seem to have 3 shipping rates enabled, so could you provide a screenshot of the config for this module?

2. You mention that this issue only affects existing customers, what does "Customer Shipping Account" does?

3. Did you try disabling this module, to see if it is the cause of your issue?

**Comment by ctadlock** [comment] 2018-04-17 16:25
Yes, I have three shipping methods enabled:
* Shipping (this extension)
* Estimate (Amasty Shipping Table rates)
* Flat rate (customer shipping account)

We use the Flat rate for customer to provide their own shipping account info at checkout; this is done with the [Amasty Order Attributes](https://amasty.com/order-attributes-for-magento-2.html) extension

The problem only manifests when using this extension, so disabling this extension wont help anything. Im still playing around to try to get a repro case that cause it to not happen, given that it happens every time.



![image](https://user-images.githubusercontent.com/1539397/38883027-acba9b38-4220-11e8-94c9-37ca52dd7bc4.png)


![image](https://user-images.githubusercontent.com/1539397/38883062-bc06f1ae-4220-11e8-8c24-a2b5a5f22c34.png)


![image](https://user-images.githubusercontent.com/1539397/38883092-cc3a58a4-4220-11e8-82e2-54bacdd6447b.png)

**Comment by srenon** [comment] 2018-04-17 20:08
When placing an order from admin by default it should only show the drop down

![image](https://user-images.githubusercontent.com/1415141/38893630-da6450dc-4258-11e8-92f1-49da8c69e04f.png)

You should check these files

MagePal/CustomShippingRate/view/adminhtml/layout/*
MagePal/CustomShippingRate/view/adminhtml/templates/order/create/shipping/method/form.phtml

If you can repoduce this issue on a blank magento install without any thirdparty then I will take a look.

**Comment by ctadlock** [comment] 2018-04-17 22:10
Those files are fine, presuming the version that is in packagist is accurate.
I have to reload the page to get it to show that UI.

**Comment by srenon** [comment] 2018-04-17 23:13
can I see a screenshot of the entire shipping method area, for when it works and when it does not

**Comment by ctadlock** [comment] 2018-04-18 16:49
1. When page is first loaded...
![image](https://user-images.githubusercontent.com/1539397/38946126-6329d074-42ed-11e8-80db-5322ae3dde40.png)

2. After adding product to cart and clicking `get shipping methods and rates`
![image](https://user-images.githubusercontent.com/1539397/38946168-8401efca-42ed-11e8-94a0-55e1e956fab2.png)

3. After pressing `return` in the browser url bar (Chrome/Mac)...
![image](https://user-images.githubusercontent.com/1539397/38946214-a308bb24-42ed-11e8-96cd-b92151f691f1.png)

4. After selecting one of the shipping rates and setting a $ value...
![image](https://user-images.githubusercontent.com/1539397/38946242-b701f064-42ed-11e8-91f7-68346e8edc83.png)

**Comment by srenon** [comment] 2018-04-18 18:03
Enabled template hints and see what template this is using... When working correctly it should be MagePal/CustomShippingRate/view/adminhtml/templates/order/create/shipping/method/form.phtml

![image](https://user-images.githubusercontent.com/1415141/38949678-18a0267e-4311-11e8-8376-364fa132f3b7.png)

**Comment by ctadlock** [comment] 2018-04-27 22:02
Good idea. Its`app/code/Wyomind/PickupAtStore/view/adminhtml/templates/shipping/order/create/shipping/method/form.phtml` when the page firsts loads, then when I press `return` in the browser url it is `vendor/magepal/magento2-customshippingrate/view/adminhtml/templates/order/create/shipping/method/form.phtml`.

Im also using the [Wyomind Advanced Inventory](https://www.wyomind.com/magento2/advanced-inventory-magento.html) extension


![image](https://user-images.githubusercontent.com/1539397/39386899-8a6977ee-4a2b-11e8-9712-33e53dab3ef6.png)


![image](https://user-images.githubusercontent.com/1539397/39386940-b3365d7c-4a2b-11e8-9e93-395e4b7ee164.png)

**Comment by srenon** [comment] 2018-04-27 23:09
I going to go ahead an closed this ticket since it is a module conflict and not a bug.

If you need further help, you are more than welcome to open a paid support ticket at support@magepal.com

**Closed by srenon** 2018-04-27 23:09 UTC
